se agrego todo lo correspondiente a la autenticación 2fa
Eider22/akinmueble_security_ms pull request #7
Opened 2023-03-19 00:27 UTC by StivenLH24

2023-03-19 00:29 UTC, Bycristian000 approved these changes

2023-03-19 00:59 UTC, jonvas06 approved these changes

2023-03-19 19:44 UTC, Eider22 commented on src/services/security-user.service.ts
> +    public repositoryuser: UserRepository,
use cammellCase   → repositoryUser

2023-03-19 19:50 UTC, Eider22 commented on src/controllers/user.controller.ts
> +    if (user) {
Change structure if-else.
First evaluates escape condition and "else"  isn´t necesary.

Something like:
if(!user){
    return new HttpErrors[401]("incorrect credentials.");
}


let code2fa = this.serviceSecurity.createTextRandom(5);
      let login: Login = new Login();
      login.userId = user._id!;
      login.code2fa = code2fa;
      login.codeState2fa = false;
      login.token = "";
      login.tokenState = false;
      this.repositoryLogin.create(login);
      // notify the user via mail or sms
      return user;

2023-03-19 19:52 UTC, Eider22 commented on src/controllers/user.controller.ts
> +    return new HttpErrors[401]("incorrect credentials.");
change "return" by  "throw"

2023-03-19 19:54 UTC, Eider22 requested changes

2023-03-19 19:54 UTC, Eider22 commented on src/controllers/user.controller.ts
> +    let user = this.serviceSecurity.identifyUser(credentials);
Use try catch

2023-03-19 20:49 UTC, Bycristian000 commented on src/controllers/user.controller.ts
> +   @post('/identify-users')
seria identify-user , segun video que esta como "identificar usuario"

2023-03-19 20:58 UTC, Eider22 commented on src/controllers/user.controller.ts
> +import {service} from '@loopback/cnpmore';
Why this dependency?

2023-03-19 20:58 UTC, Eider22 commented on src/controllers/user.controller.ts
> -import {service} from '@loopback/core';
Why delete this?

2023-03-20 02:42 UTC, Eider22 approved these changes

2023-03-20 02:43 UTC, merged